# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Auth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Auth

# Add the Firebase pod for Google Analytics
pod 'FirebaseAnalytics'

# For Analytics without IDFA collection capability, use this pod instead
# pod FirebaseAnalytics/Core

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'FirebaseAuth'


end
